# Configuração de deploy para Railway usando NIXPACKS builder
# Este arquivo configura o build e deploy do bot WhatsApp no Railway
# Resolvendo o erro persistente de dependências GTK/Puppeteer no container Alpine
# Adicionando todas as bibliotecas necessárias para Puppeteer funcionar corretamente

[build]
# Usar NIXPACKS builder para melhor compatibilidade com dependências do sistema
builder = "NIXPACKS"
# Comando executado antes do build para instalar dependências do sistema
# Necessário para Puppeteer funcionar corretamente no Railway (Alpine Linux)
preBuildCommand = "apt-get update && apt-get install -y libgobject-2.0-0 libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 fonts-liberation libgtk-3-0 libxss1 libatk1.0-0 libcairo-gobject2 libatspi2.0-0 libpango-1.0-0 libcairo2 libgdk-pixbuf2.0-0"

[deploy]
# Comando para iniciar a aplicação após o deploy
# Usa o script "start" definido no package.json
startCommand = "node index.js"